Repository xamarin/XamarinComponents, pull requests merged in 2020-11, with the labels that each got.

#873 Google.GRPC version 1.25.0 bump
  XPlat/Google.Grpc/build.cake
  XPlat/Google.Grpc/source/Xamarin.Grpc.Android.Bindings.XamarinAndroid/Xamarin.Grpc.Android.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.Api.Bindings.XamarinAndroid/Xamarin.Grpc.Api.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.Context.Bindings.XamarinAndroid/Xamarin.Grpc.Context.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.Core.Bindings.XamarinAndroid/Xamarin.Grpc.Core.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.OkHttp.Bindings.XamarinAndroid/Xamarin.Grpc.OkHttp.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.Protobuf.Lite.Bindings.XamarinAndroid/Xamarin.Grpc.Protobuf.Lite.Bindings.XamarinAndroid.csproj
  XPlat/Google.Grpc/source/Xamarin.Grpc.Stub.Bindings.XamarinAndroid/Xamarin.Grpc.Stub.Bindings.XamarinAndroid.csproj
Labels: in-progress, needs-review

#883 SceneForm bindings fixes (issue 833)
  Android/SceneForm/build.cake
  Android/SceneForm/source/Rendering/Transforms/Metadata.xml
Labels: do-not-merge, in-progress, needs-review

#874 Io.OpenCensus version 0.25 bump
  Android/Io.OpenCensus/build.cake
  Android/Io.OpenCensus/source/Xamarin.Io.OpenCensus.OpenCensusApi/Xamarin.Io.OpenCensus.OpenCensusApi.csproj
  Android/Io.OpenCensus/source/Xamarin.Io.OpenCensus.OpenCensusContribGrpcMetrics/Xamarin.Io.OpenCensus.OpenCensusContribGrpcMetrics.csproj
Labels: in-test

#936 Play.Core-1.6.5
  Android/Google.Play.Core/build.cake
  Android/Google.Play.Core/cgmanifest.json
  Android/Google.Play.Core/source/Xamarin.Google.Play.Core.XamarinAndroid/Transforms/Metadata.Namespaces.xml
  Android/Google.Play.Core/source/Xamarin.Google.Play.Core.XamarinAndroid/Transforms/Metadata.xml
  Android/Google.Play.Core/source/Xamarin.Google.Play.Core.XamarinAndroid/Xamarin.Google.Play.Core.XamarinAndroid.csproj
Labels: do-not-merge, in-progress, needs-review

#1012 [EN] Update Android to v1.7.1
  Android/ExposureNotification/build.cake
  Android/ExposureNotification/source/PlayServicesNearby/Additions/ExposureNotificationClient.cs
  Android/ExposureNotification/source/PlayServicesNearby/PlayServicesNearby.csproj
  Android/ExposureNotification/source/PlayServicesNearby/Transforms/Metadata.xml
Labels: area-ExposureNotifications
