Repository xamarin/XamarinComponents, pull requests merged in 2021-05, with the labels that each got.

#1140 kotlin-1.4.21
  Android/AndroidThings/build.cake
  Android/Kotlin/cgmanifest.json
  Android/Kotlin/config.json
  Android/Kotlin/source/Project.cshtml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.Core/Transforms/Metadata.xml
  global.json
Labels: in-progress, in-test

#1144 kotlin-1.5.0
  Android/Kotlin/cgmanifest.json
  Android/Kotlin/config.json
Labels: in-progress, in-test

#1157 Kotlin 1.4.21.1
  Android/Kotlin/cgmanifest.json
  Android/Kotlin/config.json
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.Core/Transforms/EnumFields.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.Core/Transforms/EnumMethods.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.Core/Transforms/Metadata.Namespace.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.Core/Transforms/Metadata.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.CoroutinesAndroid/Transforms/EnumFields.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.CoroutinesAndroid/Transforms/EnumMethods.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.CoroutinesAndroid/Transforms/Metadata.Namespaces.xml
  Android/Kotlin/source/Xamarin.KotlinX.Coroutines.CoroutinesAndroid/Transforms/Metadata.xml
Labels: in-progress

#1173 KotlinXCoroutines-1.4.3.1-targets-files-fixes
  Android/KotlinXCoroutines/build.cake
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Android/KotlinX.Coroutines.Android.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Android/Xamarin.KotlinX.Coroutines.Android.targets
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Core.Jvm/KotlinX.Coroutines.Core.Jvm.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Core.Jvm/Xamarin.KotlinX.Coroutines.Core.Jvm.targets
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Core/KotlinX.Coroutines.Core.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Core/Xamarin.KotlinX.Coroutines.Core.targets
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Jdk8/KotlinX.Coroutines.Jdk8.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Jdk8/Xamarin.KotlinX.Coroutines.Jdk8.targets
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Reactive/KotlinX.Coroutines.Reactive.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Reactive/Xamarin.KotlinX.Coroutines.Reactive.targets
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Rx2/KotlinX.Coroutines.Rx2.csproj
  Android/KotlinXCoroutines/source/KotlinX.Coroutines.Rx2/Xamarin.KotlinX.Coroutines.Rx2.targets
Labels: in-progress, in-test

#1164 GooglePlaces-2.4.0
  Android/GooglePlaces/GooglePlaces.sln
  Android/GooglePlaces/build.cake
  Android/GooglePlaces/cgmanifest.json
  Android/GooglePlaces/samples/PlacesSample/MainActivity.cs
  Android/GooglePlaces/samples/PlacesSample/PlacesSample.csproj
  Android/GooglePlaces/samples/PlacesSample/Properties/AndroidManifest.xml
  Android/GooglePlaces/samples/PlacesSample/Resources/layout/activity_main.axml
  Android/GooglePlaces/samples/PlacesSample/Resources/values/styles.xml
  Android/GooglePlaces/source/GooglePlaces/GooglePlaces.csproj
  Android/GooglePlaces/source/GooglePlaces/Transforms/Metadata.xml
Labels: in-progress, in-test

#1139 Binderator improvements
  Util/Xamarin.AndroidBinderator/.editorconfig
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tests/Xamarin.AndroidBinderator.Tests.csproj
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Program.cs
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.Tool/Xamarin.AndroidBinderator.Tool.csproj
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Config/BindingConfig.cs
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs
  Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator.csproj
Labels: do-not-merge, in-progress, in-test, needs-review
